[package]
name = "ceph-rbd"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
license = "MIT"

[build-dependencies]
bindgen = "0.36.0"

[dependencies]
ceph = "*"
libc = "~0.2"
log = "~0.4"
nix = "~0.10"
